language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
dist: trusty
addons:
  chrome: stable
before_install:
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
script:
  - npm run test