language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
dist: trusty
addons:
  chrome: stable
before_install:
  # start web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test